/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package Main;

import java.time.LocalDateTime;  // Import the LocalDateTime class

public class App {

    public static void main(String[] args) {
        pluralize("cat",1);
        flipNHeads(5) ;
        clock();
    }
    public static void pluralize (String s,int n){
        if(n>1){
            System.out.println("I own " + n + " "+ s +"s");
        }else {
            System.out.println("I own " + n + " "+ s);

        }

    }
    static void flipNHeads(int n){
        int c=0;
        for (int i=0 ;i<n ;i++){
            double z=(Math.random());

            if (z>0.5){
                System.out.println("head");
                c++;
            }else {
                System.out.println("tail");

            }

        }
        System.out.println("It took "+n+" flip to flip " + c + "head in a row");

    }
    static void clock (){

        LocalDateTime now = LocalDateTime.now();

        int i=1;
        int second = now.getSecond();
        i=second ;

        while (i>-1){
            LocalDateTime yet = LocalDateTime.now();
            int towSec = yet.getSecond();
            int hour = yet.getHour();
            int minute = yet.getMinute();
            while (i !=towSec){

                System.out.println("the hour is : " +hour+" :"+minute+" : "+ towSec);
                i=towSec ;
            }
        }

    }



}
