/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

public class Library {
    public static int[] roll(int number){
        int roll[]=new int[number];
        for (int i=0;i<roll.length;i++){
            int z=(int)Math.floor((Math.random()*7));
            roll[i]=z ;
        }
        return roll ;
    }
    static boolean containsDuplicates() {
        int max = 6;
        int min = 1;
        int range = max - min + 1;

        Set<Integer> s = new HashSet<Integer>();
        for (int i = 0; i < 10; i++) {
            int rand = (int) (Math.random() * range) + min;
            s.add(rand);
        }
        if (s.size() < 6) {
            return true;
        } else {
            return false;
        }
    }

    public static int calculateAvg(Integer[] n){
        int avg=0 ;
        for(int i=0;i<n.length;i++){
            avg += n[i] ;
        }
        return avg ; }

    public static int calculateTowDiemention(Integer[][] n){
        int avg=0 ,z=0,l=0,m=0;
        for(int i=0;i<n[0].length;i++){
//  avg =avg+ n[0][i] ;

            avg =avg+ n[0][i] ;
            z =z+ n[1][i] ;
            l =l+ n[2][i] ;
            m =m+ n[3][i] ;

        }
        if(z<avg && z<l &&z<m){avg=z;
        }else if(l<avg && l<z &&l<m){avg=l;
        }else if(m<avg && m<z && m<l){avg=m;
        }


        return avg  ; }

}
