/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

import java.nio.file.Path;

public class App {
  
    public static void main(String[] args) {
                System.out.println(readFile("gates.js"));
    }
     public static String readFile(String read){
        String miss ="" ;
        int num=5 ;
        Path path = Paths.get(read);
        try {
            List<String> lines = Files.readAllLines(path);
            for (int i = 0; i < lines.size(); i++) {

                if (lines.get(i).contains(";")) {

                } else if (lines.get(i).contains("{")) {

                } else if (lines.get(i).contains("}")) {

                } else if (lines.get(i).contains("if")) {

                } else if (lines.get(i).contains("else")) {

                } else if (lines.get(i).isEmpty()) {

                } else {
                    miss = miss+"Line :" + (i + 1) + " Missing semicolon " ;
                }
            }

        } catch (Exception ex) {
            System.out.println("the line te" + ex);

        }
        return miss;

    }
}
